steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/samples-433712/angular-app:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/samples-433712/angular-app:latest"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "angular-app"
      - "--image"
      - "gcr.io/samples-433712/angular-app:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"

images:
  - "gcr.io/samples-433712/angular-app:latest"

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
